%% Search for a specified operating point for the model - ball_and_beam_for_lin2.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.1 and Simulink Control Design (TM) 4.4.
%
% Generated on: 12-May-2017 23:23:05

%% Specify the model name
model = 'ball_and_beam_for_lin2';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, and Max = Inf.

% State (1) - ball_and_beam_for_lin2/Ball and Beam/Ball/PJ
% - Default model initial conditions are used to initialize optimization.
opspec.States(1).Known = true;

% State (2) - ball_and_beam_for_lin2/Ball and Beam/Ball/PJ
% - Default model initial conditions are used to initialize optimization.
opspec.States(2).Known = true;

% State (3) - ball_and_beam_for_lin2/Ball and Beam/Ball/RJ
% - Default model initial conditions are used to initialize optimization.
opspec.States(3).Known = true;

% State (4) - ball_and_beam_for_lin2/Ball and Beam/Ball/RJ
% - Default model initial conditions are used to initialize optimization.
opspec.States(4).Known = true;

% State (5) - ball_and_beam_for_lin2/Ball and Beam/RJ1
opspec.States(5).x = -0.028073;

% State (6) - ball_and_beam_for_lin2/Ball and Beam/RJ1
% - Default model initial conditions are used to initialize optimization.

% State (7) - ball_and_beam_for_lin2/Ball and Beam/RJ2
opspec.States(7).x = -1.7548;

% State (8) - ball_and_beam_for_lin2/Ball and Beam/RJ2
% - Default model initial conditions are used to initialize optimization.

% State (9) - ball_and_beam_for_lin2/Ball and Beam/RJ3
opspec.States(9).x = 1.7267;

% State (10) - ball_and_beam_for_lin2/Ball and Beam/RJ3
% - Default model initial conditions are used to initialize optimization.

% State (11) - ball_and_beam_for_lin2/Ball and Beam/Shaft/BallBearing1
% - Default model initial conditions are used to initialize optimization.

% State (12) - ball_and_beam_for_lin2/Ball and Beam/Shaft/BallBearing1
% - Default model initial conditions are used to initialize optimization.

% State (13) - ball_and_beam_for_lin2/Ball and Beam/Shaft/BallBearing2
% - Default model initial conditions are used to initialize optimization.
opspec.States(13).Known = true;

% State (14) - ball_and_beam_for_lin2/Ball and Beam/Shaft/BallBearing2
% - Default model initial conditions are used to initialize optimization.
opspec.States(14).Known = true;

% State (15) - ball_and_beam_for_lin2/Ball and Beam/Solver Configuration/EVAL_KEY/INPUT_1_1_1
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - ball_and_beam_for_lin2/In1
opspec.Inputs(1).u = -0.5600000000000001;

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - ball_and_beam_for_lin2/Out1
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(1).Known = true;

% Output (2) - ball_and_beam_for_lin2/Out2
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(2).Known = true;

% Output (3) - ball_and_beam_for_lin2/Out3
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(3).Known = true;

% Output (4) - ball_and_beam_for_lin2/Out4
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(4).Known = true;

% Output (5) - ball_and_beam_for_lin2/Out5
% - Default model initial conditions are used to initialize optimization.

%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[operating_point, operating_point_report] = findop(model,opspec,opt);
clear opt opspec model;
